# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/
# Go to as a quick way to check syntax
# Appearance


############################
## Theme
############################

# Choose a theme.
#   Latest themes (may require updating): https://sourcethemes.com/academic/themes/
#   Browse built-in themes in `themes/academic/data/themes/`
#   Browse user installed themes in `data/themes/`
theme: forest

# Enable users to switch between day and night mode?
day_night: true

# Override the theme's font set (optional).
#   Latest font sets (may require updating): https://sourcethemes.com/academic/themes/
#   Browse built-in font sets in `themes/academic/data/fonts/`
#   Browse user installed font sets in `data/fonts/`
font: 'modern'

# Choose a font size.
# Sizes: XS (extra small), S (small), M (medium), L (large - DEFAULT), XL (extra large)
font_size: L

# SEO


############################
## Basic Info
############################

# Website type
#   Improve how search engines understand your site.
#   For personal sites, choose "Person".
#   For organizations and projects, choose from https://schema.org/Organization#subtypes
#   E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization
site_type: Person

# Local business type (optional)
# If you entered "LocalBusiness" above, choose the type of business from https://schema.org/LocalBusiness#subtypes
local_business_type: ''

# Organization name (optional)
# Enter an organization or project name. Defaults to the site title from `config.toml`.
org_name: ''

# Description for social sharing and search engines. If undefined, superuser role is used in place.
description: 'A blog and portfolio for Dario Clarke'
twitter: ''

# Contact (edit or remove options as required)


############################
## Contact details
##
## These details power the Contact widget (if enabled).
## Additionally, for organizations, these details may be used to enrich search engine results.
############################

# Enter contact details (optional). To hide a field, clear it to "" or ''.
email: test@example.org
phone: ''

# Address
# For country_code, use the 2-letter ISO code (see https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2 )
# address = {street = "450 Serra Mall", city = "Stanford", region = "CA", postcode = "94305", country = "United States", country_code = "US"}
address:
  street: ''
  city: ''
  region: ''
  postcode: ''
  country: Barbados
  country_code: BB

# Geographic coordinates
# To get your coordinates, right-click on Google Maps and choose "What's here?". The coords will show up at the bottom.
# coordinates: latitude: '37.4275', longitude = '-122.1697'
coordinates:
  latitude: ''
  longitude: ''

# Directions for visitors to locate you. 'Enter Building 1 and take the stairs to Office 200 on Floor 2'
directions: ''

# Office hours
# A list of your office hours. To remove, set to an empty list `[]`.
office_hours: []

# Enter an optional link for booking appointments (e.g. 'calendly.com').
appointment_url: ''

# Contact links
#   Set to `[]` to disable, or comment out unwanted lines with a hash `#`.
contact_links:
  - icon: github
    icon_pack: fab
    name: Find Me on Github
    link: 'https://github.com/dario-j-c'
  - icon: kaggle
    icon_pack: fab
    name: Find Me on Kaggle
    link: 'https://www.kaggle.com/djclarke'
  - icon: linkedin
    icon_pack: fab
    name: Find Me on LinkedIn
    link: 'https://www.linkedin.com/in/dario-clarke-72003784/'
  - icon: telegram
    icon_pack: fab
    name: Telegram Me
    link: 'https://t.me/Dlav_J'

# Site header

# Main menu alignment (l = left, c = center, r = right) and logo options.
main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: true

# Localization


############################
## Regional Settings
############################

# Date and time format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
#   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
date_format: '02 Jan 2006'
#   Examples: "3:04 pm" or "15:04"
time_format: '3:04 PM'

# Address format (choose from the [address_formats] list below or add you own to the list).
address_format: en-us

# Site features


############################
## Site Features
############################

# Enable source code highlighting? true/false
# Documentation: https://sourcethemes.com/academic/docs/writing-markdown-latex/#highlighting-options
highlight: true
highlight_languages:
  - r
  - python
  - latex

# Enable LaTeX math rendering? true/false
#   If false, you can enable math on a per page basis as needed.
math: false

# Enable diagram rendering? true/false
#   If false, you can enable diagrams on a per page basis as needed.
diagram: false

# Privacy pack
#   Show a cookie consent message to visitors
#   Anonymize IP in Google Analytics (if enabled)
privacy_pack: false

# Enable visitors to edit pages?
#   `repo` defines the repository URL. `editable` defines which page types can be edited.
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false
show_related:
  book: true
  page: false
  post: true
  project: true
  publication: true
  event: true
# Show estimated reading time for posts? (true/false)
reading_time: true
# Display next/previous section pager? (true/false)
section_pager: false
# Display pager in Docs layout (e.g. tutorials)
docs_section_pager: true
# Enable in-built social sharing buttons? (true/false)
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
# Abstract length (characters) in the Compact and Portfolio Card list views. Also, see `summaryLength` in `config.toml`.
abstract_length: 135
# Load JS plugins
#   E.g. To load `/assets/js/custom.js`, set `plugins_js = ["custom"]`.
plugins_js: []

# Avatars.
# An avatar is an image that appears next to a user's name.
# An avatar can be uploaded as an image named `avatar` to each user's profile or fetched from Gravatar.com.
avatar:
  gravatar: false
# Choose a shape for avatar images. Options: circle, square.
  shape: circle

# Configuration of publication pages.
publications:
  # Date format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format: January 2006
  citation_style: apa

# Configuration of project pages.
projects:
  # Views for associated content.
  #   1: List
  #   2: Compact
  #   3: Card
  #   4: Citation (publications only)
  post_view: 2
  publication_view: 2
  talk_view: 2

breadcrumb:
  page_types:
    book: true

  # Comment provider:
  #   0: Disabled
  #   1: Disqus (https://disqus.com)
  #   2: Commento (https://commento.io)
comments:
  provider: ''
  commentable:
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
    
############################
## Search
############################
  # Search provider:
  #   0: No search engine
  #   1: Academic (built-in)
  #   2: Algolia (https://www.algolia.com)
search:
  provider: wowchemy
  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
    

############################
## Maps
############################
  # To show your address on a map in the Contact widget, enter your latitude and longitude (above)
  # and choose a map provider below.
  #
  # To use Google Maps, set `engine` to 1 and enter your API key that can be obtained here:
  #   https://developers.google.com/maps/documentation/javascript/get-api-key
  # To use OpenStreetMap tiles, set `engine` to 2.
  # To use OpenStreetMap on a high traffic site, set `engine` to 3 and enter your API key that can be obtained here:
  #   https://www.mapbox.com/studio/account/tokens
  #
  # Map provider:
  #   0: No map
  #   1: Google Maps
  #   2: OpenStreetMap (Mapnik)
  #   3: OpenStreetMap (Mapbox)
map:
  provider: mapnik
  api_key: ''
  zoom: 15

marketing:
  google_analytics:   'G-XTFYJD2GCK' #This is Google's measurment ID. I will see if this is fine or if I have to switch to a tacking ID, begins with U
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: master
  local_backend: false
icon:
  pack:
    ai: false


# Available address formats.
# address_formats: en-bb = {order = ['street', 'region', 'parish', 'postcode'], delimiters = [', ', ', ', ' ', '']}
